### PR TITLE
Make SDK configurable, defaulting to speculos default values

### PR DESCRIPTION
**Pull request by TamtamHero**

### CODE REVIEW

**Comment by jleni** [comment]
This change is not backwards compatible and would result in many problem.

We would need these changes to be compatible with previous versions before accepting the change

**Comment by jleni** [comment]
What are speculos default values?

**Comment by jleni** [comment]
I am worried that this change may not be backwards compatible and may introduce compatibility issues with existing apps.

**Comment by TamtamHero** [comment]
https://github.com/LedgerHQ/speculos/blob/master/speculos/main.py#L256-L257

Zemu currently use default value for Nano X but not Nano S. Current default value for Nano S would be 2.1 instead of 2.0, which shouldn't break anything as syscalls addresses are not changing from a version to another anymore.

**Pull request merged**
